### ISSUE TITLE
incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by antHeater** [ninoseki/miteru#85]
<img width="928" alt="miteru_encoding_error" src="https://user-images.githubusercontent.com/29625269/58752116-a2f7d080-84a9-11e9-9c5f-3ad709229e78.png">
Hi, sometimes it ends up with this error:

`        13: from /var/lib/gems/2.5.0/gems/miteru-0.12.2/lib/miteru/crawler.rb:34:in `block in execute'
        12: from /var/lib/gems/2.5.0/gems/miteru-0.12.2/lib/miteru/website.rb:36:in `has_kits?'
        11: from /var/lib/gems/2.5.0/gems/miteru-0.12.2/lib/miteru/website.rb:28:in `index?'
        10: from /var/lib/gems/2.5.0/gems/miteru-0.12.2/lib/miteru/website.rb:13:in `title'
         9: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/element.rb:177:in `text'
         8: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/node_set.rb:276:in `text'
         7: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/node_set.rb:276:in `each'
         6: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/node_set.rb:278:in `block in text'
         5: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/text.rb:24:in `text'
         4: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/entity_decoder.rb:5:in `try_decode'
         3: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/entity_decoder.rb:14:in `decode'
         2: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/html/entities.rb:2142:in `decode'
         1: from /var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/entities.rb:77:in `decode'
/var/lib/gems/2.5.0/gems/oga-2.15/lib/oga/xml/entities.rb:77:in `gsub': incompatible character encodings: ASCII-8BIT and UTF-8 (Encoding::CompatibilityError)`

System info: 
Ubuntu 18.04.2 LTS
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

What I'm doing wrong?

**Comment by ninoseki** [comment]
It is already fixed in v0.12.3. Please use the latest version.

**Comment by antHeater** [comment]
Still getting the same error, version installed: 0.12.4
![miteru](https://user-images.githubusercontent.com/29625269/58970603-0a6b9400-87ba-11e9-8105-56246175f562.png)
